"""Initial schema with 15 tables

Revision ID: bf2bf190408c
Revises: 
Create Date: 2026-02-06 00:03:34.001289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf2bf190408c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(length=100), nullable=False, comment='증권사명'),
    sa.Column('report_title', sa.String(length=300), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('stock_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='관련 종목 코드 배열'),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='원본 PDF URL'),
    sa.Column('minio_path', sa.String(length=500), nullable=True, comment='MinIO 저장 경로'),
    sa.Column('extracted_text', sa.Text(), nullable=True, comment='Vision API 추출 텍스트'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI 요약'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_broker_reports_broker_name', 'broker_reports', ['broker_name'], unique=False)
    op.create_index('ix_broker_reports_date', 'broker_reports', ['report_date'], unique=False)
    op.create_table('company_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_stock_code', sa.String(length=10), nullable=False),
    sa.Column('target_stock_code', sa.String(length=10), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False, comment='supplier, customer, competitor, subsidiary'),
    sa.Column('relation_detail', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True, comment='dart, news, manual'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='상세 그래프는 Neo4j에 저장, 이 테이블은 캐시/참조용'
    )
    op.create_index('ix_company_relations_source', 'company_relations', ['source_stock_code'], unique=False)
    op.create_index('ix_company_relations_target', 'company_relations', ['target_stock_code'], unique=False)
    op.create_index('ix_company_relations_type', 'company_relations', ['relation_type'], unique=False)
    op.create_table('daily_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('market_summary', sa.Text(), nullable=True, comment='시장 요약'),
    sa.Column('top_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='오늘의 키워드 배열'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('briefing_date')
    )
    op.create_index('ix_daily_briefings_date', 'daily_briefings', ['briefing_date'], unique=False)
    op.create_table('glossary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=100), nullable=False, comment='용어 (한글)'),
    sa.Column('term_en', sa.String(length=100), nullable=True, comment='용어 (영문)'),
    sa.Column('abbreviation', sa.String(length=20), nullable=True, comment='약어'),
    sa.Column('difficulty', sa.String(length=20), nullable=False, comment='beginner, elementary, intermediate'),
    sa.Column('category', sa.String(length=20), nullable=False, comment='basic, market, indicator, technical, product, strategy'),
    sa.Column('definition_short', sa.String(length=200), nullable=False, comment='한줄 정의'),
    sa.Column('definition_full', sa.Text(), nullable=True, comment='상세 설명'),
    sa.Column('example', sa.Text(), nullable=True, comment='예시'),
    sa.Column('formula', sa.String(length=200), nullable=True, comment='공식 (지표인 경우)'),
    sa.Column('related_terms', sa.Text(), nullable=True, comment='관련 용어 (쉼표 구분)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_index('ix_glossary_category', 'glossary', ['category'], unique=False)
    op.create_index('ix_glossary_difficulty', 'glossary', ['difficulty'], unique=False)
    op.create_index('ix_glossary_term', 'glossary', ['term'], unique=False)
    op.create_table('historical_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='사례 제목'),
    sa.Column('event_date', sa.Date(), nullable=True, comment='사건 발생일'),
    sa.Column('event_year', sa.Integer(), nullable=True, comment='사건 연도'),
    sa.Column('summary', sa.Text(), nullable=False, comment='사례 요약'),
    sa.Column('full_content', sa.Text(), nullable=True, comment='전체 내용 (스토리텔링)'),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='관련 키워드'),
    sa.Column('source_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='출처 URL 배열'),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_cases_event_year', 'historical_cases', ['event_year'], unique=False)
    op.create_index('ix_historical_cases_keywords', 'historical_cases', ['keywords'], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False, comment='beginner, elementary, intermediate'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('briefing_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('briefing_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False, comment='종목 코드'),
    sa.Column('stock_name', sa.String(length=100), nullable=False, comment='종목명'),
    sa.Column('change_rate', sa.Numeric(precision=10, scale=2), nullable=True, comment='등락률 (%)'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='거래량'),
    sa.Column('selection_reason', sa.String(length=50), nullable=True, comment='top_gainer, top_loser, high_volume'),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='관련 키워드'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['briefing_id'], ['daily_briefings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_briefing_stocks_briefing_id', 'briefing_stocks', ['briefing_id'], unique=False)
    op.create_index('ix_briefing_stocks_stock_code', 'briefing_stocks', ['stock_code'], unique=False)
    op.create_table('case_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_keyword', sa.String(length=100), nullable=False, comment='현재 키워드'),
    sa.Column('current_stock_code', sa.String(length=10), nullable=True, comment='현재 관련 종목'),
    sa.Column('matched_case_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=True, comment='유사도 점수 (0~1)'),
    sa.Column('match_reason', sa.Text(), nullable=True, comment='매칭 이유'),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_case_id'], ['historical_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_matches_current_keyword', 'case_matches', ['current_keyword'], unique=False)
    op.create_index('ix_case_matches_matched_at', 'case_matches', ['matched_at'], unique=False)
    op.create_table('case_stock_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True, comment='main_subject, affected, related'),
    sa.Column('impact_description', sa.Text(), nullable=True, comment='영향 설명'),
    sa.ForeignKeyConstraint(['case_id'], ['historical_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_stock_relations_case_id', 'case_stock_relations', ['case_id'], unique=False)
    op.create_index('ix_case_stock_relations_stock_code', 'case_stock_relations', ['stock_code'], unique=False)
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment='case, glossary, briefing'),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='viewed, in_progress, completed'),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', name='uq_learning_progress_user_content')
    )
    op.create_index('ix_learning_progress_content_type', 'learning_progress', ['content_type'], unique=False)
    op.create_index('ix_learning_progress_user_id', 'learning_progress', ['user_id'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_uuid', sa.UUID(), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=True, comment='briefing, case, comparison, glossary'),
    sa.Column('context_id', sa.Integer(), nullable=True, comment='관련 컨텐츠 ID'),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_uuid')
    )
    op.create_index('ix_tutor_sessions_session_uuid', 'tutor_sessions', ['session_uuid'], unique=False)
    op.create_index('ix_tutor_sessions_user_id', 'tutor_sessions', ['user_id'], unique=False)
    op.create_table('user_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_name', sa.String(length=100), nullable=False),
    sa.Column('initial_cash', sa.BigInteger(), nullable=False, comment='초기 자금 (원)'),
    sa.Column('current_cash', sa.BigInteger(), nullable=True, comment='현재 현금'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_portfolios_user_id', 'user_portfolios', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False, comment='light, dark'),
    sa.Column('push_notification', sa.Boolean(), nullable=False),
    sa.Column('morning_briefing_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=15, scale=2), nullable=False, comment='평균 매입가'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['user_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_holdings_portfolio_id', 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_index('ix_portfolio_holdings_stock_code', 'portfolio_holdings', ['stock_code'], unique=False)
    op.create_table('simulation_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False, comment='buy, sell'),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('trade_reason', sa.Text(), nullable=True, comment='거래 사유 (학습 기록)'),
    sa.Column('traded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['user_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulation_trades_portfolio_id', 'simulation_trades', ['portfolio_id'], unique=False)
    op.create_index('ix_simulation_trades_traded_at', 'simulation_trades', ['traded_at'], unique=False)
    op.create_table('tutor_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user, assistant'),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('term_asked', sa.String(length=100), nullable=True, comment='질문한 용어 (있는 경우)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['tutor_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tutor_messages_created_at', 'tutor_messages', ['created_at'], unique=False)
    op.create_index('ix_tutor_messages_session_id', 'tutor_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tutor_messages_session_id', table_name='tutor_messages')
    op.drop_index('ix_tutor_messages_created_at', table_name='tutor_messages')
    op.drop_table('tutor_messages')
    op.drop_index('ix_simulation_trades_traded_at', table_name='simulation_trades')
    op.drop_index('ix_simulation_trades_portfolio_id', table_name='simulation_trades')
    op.drop_table('simulation_trades')
    op.drop_index('ix_portfolio_holdings_stock_code', table_name='portfolio_holdings')
    op.drop_index('ix_portfolio_holdings_portfolio_id', table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_table('user_settings')
    op.drop_index('ix_user_portfolios_user_id', table_name='user_portfolios')
    op.drop_table('user_portfolios')
    op.drop_index('ix_tutor_sessions_user_id', table_name='tutor_sessions')
    op.drop_index('ix_tutor_sessions_session_uuid', table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index('ix_learning_progress_user_id', table_name='learning_progress')
    op.drop_index('ix_learning_progress_content_type', table_name='learning_progress')
    op.drop_table('learning_progress')
    op.drop_index('ix_case_stock_relations_stock_code', table_name='case_stock_relations')
    op.drop_index('ix_case_stock_relations_case_id', table_name='case_stock_relations')
    op.drop_table('case_stock_relations')
    op.drop_index('ix_case_matches_matched_at', table_name='case_matches')
    op.drop_index('ix_case_matches_current_keyword', table_name='case_matches')
    op.drop_table('case_matches')
    op.drop_index('ix_briefing_stocks_stock_code', table_name='briefing_stocks')
    op.drop_index('ix_briefing_stocks_briefing_id', table_name='briefing_stocks')
    op.drop_table('briefing_stocks')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_historical_cases_keywords', table_name='historical_cases', postgresql_using='gin')
    op.drop_index('ix_historical_cases_event_year', table_name='historical_cases')
    op.drop_table('historical_cases')
    op.drop_index('ix_glossary_term', table_name='glossary')
    op.drop_index('ix_glossary_difficulty', table_name='glossary')
    op.drop_index('ix_glossary_category', table_name='glossary')
    op.drop_table('glossary')
    op.drop_index('ix_daily_briefings_date', table_name='daily_briefings')
    op.drop_table('daily_briefings')
    op.drop_index('ix_company_relations_type', table_name='company_relations')
    op.drop_index('ix_company_relations_target', table_name='company_relations')
    op.drop_index('ix_company_relations_source', table_name='company_relations')
    op.drop_table('company_relations')
    op.drop_index('ix_broker_reports_date', table_name='broker_reports')
    op.drop_index('ix_broker_reports_broker_name', table_name='broker_reports')
    op.drop_table('broker_reports')
    # ### end Alembic commands ###
